"""add_theme_colors_and_orders

Revision ID: 3af394f10c88
Revises: 8ec0a7c14801
Create Date: 2026-08-11 20:38:14.700665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3af394f10c88'
down_revision: Union[str, Sequence[str], None] = '8ec0a7c14801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_info', sa.Column('primary_color', sa.String(length=50), nullable=True))
    op.add_column('company_info', sa.Column('secondary_color', sa.String(length=50), nullable=True))
    op.add_column('company_info', sa.Column('accent_color', sa.String(length=50), nullable=True))
    op.add_column('company_info', sa.Column('theme_mode', sa.String(length=20), nullable=True))
    op.add_column('home_hero', sa.Column('banner_images', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_hero', 'banner_images')
    op.drop_column('company_info', 'theme_mode')
    op.drop_column('company_info', 'accent_color')
    op.drop_column('company_info', 'secondary_color')
    op.drop_column('company_info', 'primary_color')
    # ### end Alembic commands ###
